name: TV Card
description: 📺 TV Remote Card
type: lovelace
keywords:
  - tvcard
  - remote
  - tv
  - television
author:
  name: kicur
license: Apache License, Version 2.0
files:
  - tv-card-kicur.js
  - tv-card-kicur-editor.js
